baseurl = "https://ajanthan.github.io"
title = "All about what i do"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."

[author]
    name = "Ajanthan Balachandran"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Personal Blog"
  Author = "Ajanthan Balachandran"
  email = "balaajanthan@gmail.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/ajanthan_bkayts"
[[params.social]]
    title = "github"
    url = "https://github.com/ajanthan"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/ajanthanbalachandran"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180

